### ISSUE TITLE
Update Desmos Profile for an account

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#180]
This story relates to #179 . A user is able to update its own `Desmos Profile` as information of `Desmos Profile` may have been changed. This can be done in the same way as #179 as it's the same on-chain message. The UI should effectively show the user is updating the profile.

**Comment by kanniec826** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/180?planning-poker) with ZenHub @calvinkei @Rooty2020
