### ISSUE TITLE
Path to add ledger not clear

### ISSUE THREAD

**Issue by rav-11** [forbole/forbole-x#193]
When adding an account from ledger, you have to click "I have 12 / 24 word secret recovery phrase".

It's not clear that you can import a ledger wallet from this option until you click it - I think it would be better to have a 3rd option on the getting started screen like "I have a ledger wallet".

**Comment by kanniec826** [comment]
Kwun will discuss with Rooty

**Comment by kwunyeung** [comment]
I have discussed with @Rooty2020 . The original intention of having the two icons for the first step is good. It separate the flow for users who have wallet(s) or do not have wallet(s).

The flow can be clearer with the 1st option as "Import Wallet" and the 2nd option as "Create Wallet".
