### ISSUE TITLE
Handle proposals type other than Text Proposal

### ISSUE THREAD

**Issue by calvinkei** [forbole/forbole-x#203]
The current UI only works for Text Proposal. Have to add more fields for other types of proposals

**Comment by kanniec826** [comment]
@rachelhox Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/203?planning-poker)
