### ISSUE TITLE
Import recovery phrase but connecting Ledger when creating wallet

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#206]
I'm testing the flow of creating a new wallet. After confirming the secret recovery phrase, it cannot generate the wallet and the error message is about connecting Ledger.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/12be663c-3bbf-4573-bb2b-bff074b28aea)

**Comment by kwunyeung** [comment]
I'm testing the flow of creating a new wallet. After confirming the secret recovery phrase, it cannot generate the wallet and the error message is about connecting Ledger.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/12be663c-3bbf-4573-bb2b-bff074b28aea)

**Comment by kwunyeung** [comment]
Tested again. It works if the page is not connected to Ledger. Somehow it goes to the Ledger flow if a Ledger is connected.

**Comment by kanniec826** [comment]
@calvinkei Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/206?planning-poker)
