### ISSUE TITLE
Connect Ledger failed with Desmos app

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#207]
When adding new wallet with Ledger, it doesn't detect the correct Ledger app and hang there. I will pass if I open `Cosmos` app but not `Desmos` app.

Also this page should prompt users to open the correct app before continuing.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/2711e47d-a17f-4ba3-a3b2-7c59f131384a)

As Ledger app decides which coin is going to be supported, the flow for adding wallet from Ledger should be updated as

1. Set moniker to the wallet and choose coin to add
2. Prompt which Ledger app to open
3. Add the wallet with the first account

**Comment by kwunyeung** [comment]
When adding new wallet with Ledger, it doesn't detect the correct Ledger app and hang there. I will pass if I open `Cosmos` app but not `Desmos` app.

Also this page should prompt users to open the correct app before continuing.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/2711e47d-a17f-4ba3-a3b2-7c59f131384a)

As Ledger app decides which coin is going to be supported, the flow for adding wallet from Ledger should be updated as

1. Set moniker to the wallet and choose coin to add
2. Prompt which Ledger app to open
3. Add the wallet with the first account

**Comment by kanniec826** [comment]
@calvinkei Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/207?planning-poker)
