### ISSUE TITLE
Wrong content

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#208]
I think it means `Forbole X` here 😅. And we better rewrite this piece of content.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9e62e8c2-b08b-4ee0-b26e-861e741bcd69)

**Comment by kwunyeung** [comment]
I think it means `Forbole X` here 😅. And we better rewrite this piece of content.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9e62e8c2-b08b-4ee0-b26e-861e741bcd69)

**Comment by kanniec826** [comment]
@Rooty2020 Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/208?planning-poker)

**Comment by Rooty2020** [comment]
Hi team,
@rachelhox 

Please update content and remove what's recovery phrase.

https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0-2021-04?page-id=192%3A2&node-id=335%3A5791&viewport=241%2C48%2C0.86&scaling=scale-down&starting-point-node-id=267%3A2009&show-proto-sidebar=1
Screenshot 2021-08-24 at 2.45.04 PM.png

Remove create a wallet.
Screenshot 2021-08-24 at 2.48.28 PM.png
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0-2021-04?page-id=192%3A2&node-id=195%3A167&viewport=241%2C48%2C0.86&scaling=scale-down&starting-point-node-id=267%3A2009&show-proto-sidebar=1
