### ISSUE TITLE
Starred account is not following account name

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#211]
Starred account is showing the token name instead of the account name now.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/c4856636-c5c4-4c35-ae0f-071cd5d082d1)

**Comment by kwunyeung** [comment]
Starred account is showing the token name instead of the account name now.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/c4856636-c5c4-4c35-ae0f-071cd5d082d1)

**Comment by kanniec826** [comment]
@rachelhox Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/211?planning-poker)
