### ISSUE TITLE
Showing validator status during delegation

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#212]
We can show the validator status next to the names of the validators. This indicates whether the validator is active or not and the recent performance.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/72df893e-1777-47d7-acb8-5e39e8736d2d)

**Comment by kwunyeung** [comment]
We can show the validator status next to the names of the validators. This indicates whether the validator is active or not and the recent performance.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/72df893e-1777-47d7-acb8-5e39e8736d2d)

**Comment by kanniec826** [comment]
@rachelhox Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/212?planning-poker)
