### ISSUE TITLE
Fill the correct content for status

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#213]
Let's put the correct content for this context popup. 

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9168950f-f1f6-48a9-ae74-ad29c46dfc85)

I think we can put the same content as on Big Dipper.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/0d0233d6-9259-4d96-a029-85e6d5776503)

**Comment by kwunyeung** [comment]
Let's put the correct content for this context popup. 

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9168950f-f1f6-48a9-ae74-ad29c46dfc85)

I think we can put the same content as on Big Dipper.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/0d0233d6-9259-4d96-a029-85e6d5776503)

**Comment by kanniec826** [comment]
@rachelhox Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/213?planning-poker)
