### ISSUE TITLE
Support different account types

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#217]
Testing sending transaction with Ledger. The process stopped at the following stage.

![image](https://user-images.githubusercontent.com/932636/126296584-c87f381a-fdd7-45a7-8b7b-83baba1300b4.png)

Here is the error message

```
Uncaught (in promise) Error: Unsupported type: '/desmos.profiles.v1beta1.Profile'
    at Object.t.accountFromAny (c6cbca47150a1a8ba0db4a890a631ea88254b606.492c842ec1cade501903.js:1)
    at f.getAccount (c6cbca47150a1a8ba0db4a890a631ea88254b606.492c842ec1cade501903.js:1)
    at async f.getSequence (c6cbca47150a1a8ba0db4a890a631ea88254b606.492c842ec1cade501903.js:1)
```
This account is an account with a `Profile` which make it not a `BaseAccount`. https://morpheus.desmos.network/accounts/desmos1cw28l0crm2q6nktcjx7rpv28umump4s93vffw0

In Desmos, we have implemented `BaseAccount` and created the `Profile` account type. There are also a few other [vesting account types](https://github.com/cosmos/cosmos-sdk/blob/master/x/auth/spec/05_vesting.md#vesting-account-types) in Cosmos which we have to support.

**Comment by kanniec826** [comment]
@calvinkei Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/217?planning-poker)

**Comment by kanniec826** [comment]
Error after launching to mainnet

**Comment by calvinkei** [comment]
same error as https://github.com/forbole/forbole-x/issues/249
only happens for desmos profile account on mainnet
