### ISSUE TITLE
Delegation amount does not change based on the input value

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#246]
Flow: 
1. Click on "Delegate" 
2. Input any amount  (eg. 100 tokens)
3. Go to the next page, and change that amount to 50 tokens

The amount on the bottom and top of the dialogue does not bet updated

![screenshot-x forbole com-2021 09 02-15_46_04](https://user-images.githubusercontent.com/9119016/131854931-243c3868-e5ad-4d85-b187-c0e17509728a.png)

**Comment by kanniec826** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/246?planning-poker) with ZenHub @calvinkei @Rooty2020

**Comment by Rooty2020** [comment]
Hi @calvinkei ,
After disscussing with kwun, the delegation flow was updated.
1.Input target delegation amount
2.Select validator(s)
3.adjust delegation amount
4.sign

Please check the latest UI here.
https://www.figma.com/file/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0-2021-04?node-id=192%3A2

**Comment by calvinkei** [comment]
@Rooty2020 i skipped the 2nd step for now and will leave it to the next sprint. new design for step 3 are implemented to fix the issue @RiccardoM mentioned
