### ISSUE TITLE
Delegation to multiple validators fail with "index out of range"

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#249]
Flow: 
1. Try delegating to multiple validators from the favourite list
2. Confirm the transaction on the confirmation popup

The popup will error with "index out of range X + Y > Z"
![Screenshot from 2021-09-02 15-51-43](https://user-images.githubusercontent.com/9119016/131856078-8655b585-b94b-4984-9d23-e68725c90179.png)

**Comment by calvinkei** [comment]
@RiccardoM  cannot reproduce this, and it seems to be an error returned from the rpc endpoint when broadcasting. are you using a ledger? if so can you check if the transaction sent to the ledger is correct?

**Comment by RiccardoM** [comment]
@calvinkei Yes, I'm using a Ledger. I see the error is shown inside the console even before confirming the transaction:

![Capture](https://user-images.githubusercontent.com/9119016/131965472-b7ebc880-4c15-43f2-b95a-dd2dbe371524.PNG)
