### ISSUE TITLE
Address should be clickable

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#253]

**Comment by Rooty2020** [comment]
Allow user to click address.
![Screenshot 2021-09-03 at 6.19.33 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/f7b0ea6b-3964-4c9c-bdd9-68a846e98f4e)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/253?planning-poker) with ZenHub @rachelhox
