### ISSUE TITLE
Delegation should not be shown by voting power

### ISSUE THREAD

**Issue by ryuash** [forbole/forbole-x#265]
Currently the delegate component displays by voting power

![image](https://user-images.githubusercontent.com/42913823/132283871-4708f3db-4093-4882-94bf-f1cf2faa1738.png)

I suggest we follow the big dipper model and display it by name instead. As voting power display has long been known to hurt a lot validators in the long run

**Comment by kwunyeung** [comment]
It's now being displayed in random order in validator drop down menu.
