### ISSUE TITLE
Markdown support in proposal description

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#273]
Proposal description may be submitted with Markdown. The description should have markdown support to display the content correctly.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/00769f54-4aa8-4c99-975f-c242bf372591)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/273?planning-poker) with ZenHub @rachelhox
