### ISSUE TITLE
Proposal detail not being shown

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#275]
The proposal 1 on Desmos is submitted and can be shown in the proposal page but it's showing undefined in the detail page.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/9bedbb34-5b0e-4ff0-8534-dc359b12b36e)

Also should the url uses `chain-id` in the path instead of `DSM`?

**Comment by RiccardoM** [comment]
Just want to add that also votes and deposits are not shown: 
![screenshot-x forbole com-2021 09 08-07_33_15](https://user-images.githubusercontent.com/9119016/132452350-968443b9-f2ac-4b09-a84c-794f486eb977.png)


On BigDipper the data are shown properly: 
![screenshot-explorer desmos network-2021 09 08-07_34_07](https://user-images.githubusercontent.com/9119016/132452405-cb33b0e4-30c4-424b-9c96-9e667f7eded7.png)
