### ISSUE TITLE
Cannot vote from within the proposal details

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#277]
Currently it's possible to vote a proposal only from the proposals page, not from the details: 

![screenshot-x forbole com-2021 09 08-07_34_34](https://user-images.githubusercontent.com/9119016/132452561-dd7451f1-54ae-4251-b656-29b8c6728256.png)

![screenshot-x forbole com-2021 09 08-07_33_15](https://user-images.githubusercontent.com/9119016/132452607-8e10ab6d-cdd9-47a7-a37f-629cc07c07a4.png)

**Comment by kwunyeung** [comment]
This could be resolved if #275 is fixed.
