### ISSUE TITLE
Continuously prompted to insert the password

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#278]
Currently, each time the page refreshes or is closed, we are prompted to insert the password: 

![Screenshot from 2021-09-08 07-30-36](https://user-images.githubusercontent.com/9119016/132453827-f5de1811-8a4d-462f-ad7d-97f199f99b0b.png)

The same prompt is also shown if we have the web page opened and we click on the extension: the latter will require us to log in again. 

I think it would be better to have a sort of time limit between log ins. When you log in once, you are kept logged in for the next X (maybe 30) minutes so that you can navigate however you want without any problem.

**Comment by calvinkei** [comment]
duplicate #325
