### ISSUE TITLE
Clicking on address book address lead to TypeError

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#283]
Currently clicking on a stored address in the address book lead to an error inside the X application.
Step to reproduce:

1. Save an address inside the address book;
2. Click on the saved address;

The error is the following:
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

![Screenshot 2021-09-08 at 15 16 15](https://user-images.githubusercontent.com/26248202/132516829-2c5cd750-ea3d-494a-b0c1-484c099f2570.png)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/283?planning-poker) with ZenHub @calvinkei
