### ISSUE TITLE
Show address on Ledger for confirmation

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#284]
Ledger HQ requires us to show the address on Ledger device when we add an account for users to verify the address in order to make the Desmos Ledger app in public mode. The best way to add this would be when adding the first account. @Rooty2020 we may need one more screen for the address confirmation before the account is imported.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/284?planning-poker) with ZenHub @calvinkei
