### ISSUE TITLE
social media icon 

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#286]
![Screenshot 2021-09-09 at 10.55.09 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/c4405a80-9e76-4da1-8e3f-d0fd6ab3651d)
Please update social media icons.
(https://images.zenhubusercontent.com/6111e85453613f2c8109c600/9c3b3b77-1a64-4e54-ab7c-7cb3ef38622d)
https://drive.google.com/drive/folders/1jtqDYmcoJrBmgJAT8msTQ6uLSwHCt0WJ?usp=sharing

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/286?planning-poker) with ZenHub @rachelhox
