### ISSUE TITLE
Clicking on the address or moniker should directly go to the account details

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#288]
Clicking on the address or moniker should directly go to the account details
![Screenshot 2021-09-09 at 11.47.11 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/42b8539a-05d4-471c-8602-6c73e4c8ce38)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/288?planning-poker) with ZenHub @rachelhox
