### ISSUE TITLE
Remove divider

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#291]
Please remove the divider of the last proposal 
![Screenshot 2021-09-09 at 3.04.02 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/a666b1ce-e336-4cf8-8e69-69e9b95d2cda)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/291?planning-poker) with ZenHub @rachelhox
