### ISSUE TITLE
Text placeholder in Delegate page

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#297]
Browsing inside the _Delegate_ section, I've found out that hoovering over Status display a text placeholder "lore ipsum"
![Schermata 2021-09-09 alle 16 25 43](https://user-images.githubusercontent.com/26248202/132820118-4d78844a-4c83-41c0-ac9c-572c864e4d56.png)

**Comment by kwunyeung** [comment]
This has been updated and aligned with BD.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/4aa9b4fa-c351-48cd-b0bb-003518ed6e81)
