### ISSUE TITLE
Show vesting period and amount

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#299]

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/299?planning-poker) with ZenHub @Rooty2020

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/299?planning-poker) with ZenHub @calvinkei

**Comment by Rooty2020** [comment]
@calvinkei 
The UI is ready.
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=3451%3A201873&viewport=241%2C48%2C0.24&scaling=scale-down&starting-point-node-id=3992%3A239605

**Comment by calvinkei** [comment]
BDJuno will starts to support querying vesting tokens and periods next week. This task is blocked until then
