### ISSUE TITLE
Balances on Portfolio page is not correct

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#300]
This is the balance of an account on _Portfolio_ page.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/5035db31-a650-4c4d-b98e-a0b4c3a12fb6)

And this is the balance on _Account_ page.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/efaac270-6a9e-42b4-aafb-58931d9c1179)

They don't match after I have done a redelegation.

Checked against a full node and the amount on _Portfolio_ page is wrong.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/300?planning-poker) with ZenHub @calvinkei
