### ISSUE TITLE
Add Ledger BLE support 

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#301]
Add Bluetooth support for X on web so that Ledger Nano X users don't have to always connect with USB.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/301?planning-poker) with ZenHub @rachelhox

**Comment by calvinkei** [comment]
duplicate #409
