### ISSUE TITLE
UI when trying to expand the Window on the Delegation Confirmation Page

### ISSUE THREAD

**Issue by kanniec826** [forbole/forbole-x#303]

**Comment by kanniec826** [comment]
As a user, when I tried to expand the delegation confirmation page, it stays on the top left hand corner while the remaining background color is white. 
![image.png](https://images.zenhubusercontent.com/610cd72d94b503197fd1700a/3de730ec-749d-4975-a079-d707159d6e03)

![image.png](https://images.zenhubusercontent.com/610cd72d94b503197fd1700a/21b2393e-00cf-4bee-a984-3aabf5b22e81)

**Comment by kwunyeung** [comment]
@kanniec826 I think this is the default behaviour of the `iframe` in side the popup window. It is intended to fix the size of the popup. I don't think this can be fixed. Closing now.
