### ISSUE TITLE
"Send" recipient selection break the app

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#304]
Clicking the recipient field inside the "send" section break the app with this error:
![Schermata 2021-09-13 alle 10 34 41](https://user-images.githubusercontent.com/26248202/133051750-b55ab530-5102-4702-91f5-17d3c594cb41.png)

**Comment by kwunyeung** [comment]
@bragaz can you check again and see if this is fixed?

**Comment by bragaz** [comment]
Tested it and yes, it has been fixed
