### ISSUE TITLE
Error when trying editing reward address

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#306]
Actually when trying to edit the reward address inside the wallets section an error showed up making impossible to complete the operation.
![Schermata 2021-09-13 alle 14 41 54](https://user-images.githubusercontent.com/26248202/133085364-3517abe0-7019-485d-92ee-276ad934e059.png)

**Comment by kwunyeung** [comment]
This should be fixed with #112

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/306?planning-poker) with ZenHub @calvinkei

**Comment by calvinkei** [comment]
duplicate with #112
