### ISSUE TITLE
Typo on left menu on x.forbole.com

### ISSUE THREAD

**Issue by terencesflam** [forbole/forbole-x#314]
![Screenshot 2021-09-15 at 2 51 59 PM](https://user-images.githubusercontent.com/34306139/133384799-72be14bd-11bd-4176-933e-daab44f4201d.png)

At the bottom button, should be "Start Now" instead of "Star Now"

**Comment by kwunyeung** [comment]
The term is correct as that button is to hint users to `Star` some accounts now. @terencesflam do you have any suggestion if this is unclear?
