### ISSUE TITLE
Ledger warning typos

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#316]
When you try to withdraw the rewards using a Ledger account, the following alert is displayed: 

> Due to the limitation of Ledgr device, using Ledger Nano S, Forbole X  can olny withdraw rewards from up to 5 validators at a time. Using Ledger Nano X, Forbole X  can olny withdraw rewards from 20 validators at a time.

This contains some typos. Here is the correct version: 

> Due to the limitation of **Ledger** device, using Ledger Nano S, Forbole X  can **only** withdraw rewards from up to 5 validators at a time. Using Ledger Nano X, Forbole X  can **only** withdraw rewards from 20 validators at a time.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/316?planning-poker) with ZenHub @rachelhox
