### ISSUE TITLE
Manage context menu not visible on extension

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#319]
If the name of the delegated validator is too long, the `Manage` context menu can't be shown properly.

![Screen Shot 2021-09-16 at 8 27 03 AM](https://user-images.githubusercontent.com/932636/133649837-df5891a8-11fc-4f29-b228-89e21befaa44.png)

Better chop the validator name and leave room for the context menu button.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/319?planning-poker) with ZenHub @rachelhox
