### ISSUE TITLE
addressbook, commissions & edit reward address

### ISSUE THREAD

**Issue by koen84** [forbole/forbole-x#331]
There seems to be several problems with forbole X :

* clicking on an address in the address results in 
`Application error: a client-side exception has occurred (see the browser console for more information).`
from the js console 
`framework-f265d9953146294e838d.js:1 TypeError: Cannot read property 'address' of undefined`

* commissions aren't displaying at all when the validator key is imported (looks correct on big dipper)

* changing the reward address doesn't work, on the confirm screen (after flipping on "view data") 
```
"ERROR":{
"message":"src property must be a valid json object"
}
```
I suspect it's failing to get gas cost, as it stays zero.

**Comment by calvinkei** [comment]
cannot reproduce on the latest version v0.10.2
