### ISSUE TITLE
Changing page size inside withdraw rewards popup makes everything disappear

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#335]
If I try to change the page size inside the withdraw rewards popup, the list of validators disappears. It appears back if I set it to 10 though: 
![Screenshot from 2021-09-23 08-11-17](https://user-images.githubusercontent.com/9119016/134461679-2ea48969-da2d-4d11-87a6-19e77f221f56.png)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/335?planning-poker) with ZenHub @rachelhox
