### ISSUE TITLE
Get gas estimate before signing tx

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#337]
Cosmos node actually have an endpoint for estimating gas 
```
POST /cosmos/tx/v1beta1/simulate
```
I don't know why this is not included in `cosmjs`. However, the gas estimate is not accurate and we need to adjust the gas limit by x1.5. 

As a user on X, I would like to get a gas estimate before signing the transaction as I can have a better control on the gas fee I am going to spend.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/337?planning-poker) with ZenHub @calvinkei
