### ISSUE TITLE
Change text color 

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#355]
It should be  [font 2 color] #9D9D9D
![Screenshot 2021-10-02 at 2.24.12 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/a9be8ffd-bba4-4634-9ff3-f73f074d8807)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/355?planning-poker) with ZenHub @rachelhox
