### ISSUE TITLE
【Extension UI】Desmos profile for an account

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#359]

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/359?planning-poker) with ZenHub @Rooty2020

**Comment by kanniec826** [comment]
I need to change this to Epic @Rooty2020

**Comment by kanniec826** [comment]
Epic created. Move to Done
