### ISSUE TITLE
Styles blocking UI in certain screen sizes

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#363]
![6edf2ebf-4a28-4778-a2ce-ff0bdc285bd6.JPG](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/ea216ba2-e790-43c4-8272-234f13e6af66)
![d55ed62c-b209-473b-8de3-552e72eddfd9.JPG](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/2617c368-84ec-496e-aa28-6f69e9ae161a)
![76333ec8-9671-4acb-b7eb-94c9d655798c.JPG](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/ec2d7b2e-4938-4c79-9042-bcf341786e08)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/363?planning-poker) with ZenHub @calvinkei
