### ISSUE TITLE
Remove commission amount from delegator account details

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#365]
Remove commission amount from delegator account details
![Screenshot 2021-10-05 at 1.52.01 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/292a4d8f-a1a6-4b75-bd9d-c5e24bc7779a)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/365?planning-poker) with ZenHub @rachelhox
