### ISSUE TITLE
Change text and icon color

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#378]
1. Change the icon and text color
2. Change "s"elect from lowercase to uppercase

![Screenshot 2021-10-07 at 2.10.16 AM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/34ff2f4b-c0f9-4da6-9cfb-3695e21179ba)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/378?planning-poker) with ZenHub @rachelhox
