### ISSUE TITLE
Portfoglio graph does not allow to change wallet

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#400]
Currently the graph inside the _Portfolio_ page does not allow to select a wallet different from the first inserted 

![screenshot-x forbole com-2021 10 25-19_07_18](https://user-images.githubusercontent.com/9119016/138739584-2ac24185-8787-4a0f-a713-3873d10d0d6b.png)

**Comment by calvinkei** [comment]
@RiccardoM i cannot reproduce the issue. did you create a new `account` or new `wallet`? can you take a screenshot of the `wallets` page?

**Comment by RiccardoM** [comment]
@calvinkei I've created a new _account_ inside the same _wallet_. I've just noticed the _Portfolio_ page is drawing the graph based on an _wallet_ rather than on an _account_ so I guess this is not a bug rather a feature. Closing this
