### ISSUE TITLE
DSM airdrop calculation result page

### ISSUE THREAD

**Issue by kanniec826** [forbole/forbole-x#432]
Below should be able to show on the calculation page:
1. Calculation result (Amt. of DSM airdrop user can get)
2. Wallet address
3. Showing the list of roles users belongs to (if have)
e.g. 
Kava Staker & Forbole Delegator 
Atom Staker 

4. Able to proceed to next step ("Claim Now" button)

![image.png](https://images.zenhubusercontent.com/610cd72d94b503197fd1700a/b03c16aa-74e5-4acd-9fda-037ecdb0e82a)

**Comment by kanniec826** [comment]
@kwunyeung Please review

**Comment by kwunyeung** [comment]
@Rooty2020 should this be linked to the https://airdrop.desmos.network when the airdrop is claimable?

**Comment by Rooty2020** [comment]
@kwunyeung 
Please check the flow of claiming  DSM Airdrop  on Forbole X web.
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=4925%3A283664&viewport=241%2C48%2C0.11&scaling=scale-down&starting-point-node-id=4935%3A286701&show-proto-sidebar=1
