### ISSUE TITLE
DSM Airdrop UI Updated

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#454]
After discussing with @kwunyeung , We would like to add more detailed information about DSM airdrop on the calculation screen.
Here is the latest updated UI.
![Screenshot 2021-11-26 at 3.31.58 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/af6bbc82-bcea-42dd-96e2-0a7b68f4dc1d)

If the user has claimed all DSM airdrop, when he checks the DSM airdrop, he will see the calculation screen without the claim now button.
![Screenshot 2021-11-26 at 3.35.38 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/880b4397-c2d2-4a2d-9b9d-3bbea37359fc)

@RiccardoM @manu0466 
Please let us know if we can support these data.

**Comment by RiccardoM** [comment]
@Rooty2020 Yes, already supported
