### ISSUE TITLE
Rename of Cosmos Hub and Cosmos Ledger app

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#458]
We better state clearer on the network name and the app to avoid continuous confusions.

![image](https://user-images.githubusercontent.com/932636/143774193-5ccbb058-0454-4b1e-afcc-93b569140880.png)

![image](https://user-images.githubusercontent.com/932636/143774412-d37506b1-5e77-40e5-a368-3fbdea19e8b1.png)

When we should the connections, we should name it as `Cosmos Hub`.

![image](https://user-images.githubusercontent.com/932636/143774449-6349d50d-c172-421c-9048-27c6bd4dec7e.png)

When we name the Ledger app, I prefer we call it `Cosmos (ATOM)` which is what Ledger Live is using.

**Comment by calvinkei** [comment]
fixed and ready to deploy in v0.14.0
