### ISSUE TITLE
Addresses not being generated by Ledger app on chain link

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#459]
Here is a list of the network that addresses are not being generated by Cosmos (ATOM) Ledger app. They all give the same error.

![image](https://user-images.githubusercontent.com/932636/143774901-78ed25b0-7260-48da-b001-2d60575e6601.png)

1. Terra
2. Band
3. Crypto.org
3. Secret Network
4. Persistence
5. Bitsong

I can generate `Terra` and `Crypto.org` addresses with their apps. Can't install `Band` app on my Ledger and can't test with it.

**Comment by calvinkei** [comment]
@kwunyeung it's a coin type issue and should be fixed in v0.13.2. docker image updated but not deployed on x.forbole.com yet. probably too many images?

**Comment by kwunyeung** [comment]
@calvinkei deployed. Tested and it works.

**Comment by calvinkei** [comment]
@kwunyeung cool, i will close this issue then
