### ISSUE TITLE
Chainlink use private key to sign message 

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#464]
Got some feedbacks hoping X would allow uploading private keys to create a wallet as they might have their wallet created with other means than a 24-word recovery phrase.

**Comment by Rooty2020** [comment]
@calvinkei 
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=195%3A167&viewport=241%2C48%2C0.19&scaling=scale-down&starting-point-node-id=195%3A167&show-proto-sidebar=1

**Comment by nicoletting** [comment]
@calvinkei 
please download icon here:
https://drive.google.com/drive/folders/1dfW8E4NXeD7YshMTPksBER-CGt-k1Ahd?usp=sharing
