### ISSUE TITLE
Grant request for the account without DSM

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#466]
The grant flow of the account without DSM is ready.
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=5360%3A294756&viewport=241%2C48%2C0.08&scaling=scale-down&starting-point-node-id=5360%3A294756&show-proto-sidebar=1

@calvinkei 
Please assign our teammates to update it. thanks

**Comment by calvinkei** [comment]
added and ready to deploy in v0.14.0
