### ISSUE TITLE
Kava logo is not updated

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#477]
The current Kava logo is an old version.

![image](https://user-images.githubusercontent.com/932636/144411228-cfba22cb-82a2-4da5-b8a1-3094d2984946.png)

The latest version can be found on their website.

https://www.kava.io/brand-assets

**Comment by kwunyeung** [comment]
@Rooty2020 @nicoletting Please help to make the Kava logo become a circular icon with a background showing the full `K` in it.

![image](https://user-images.githubusercontent.com/932636/145156225-f70fdbe2-b3e9-4be6-b872-84ad1f7f65ee.png)

**Comment by nicoletting** [comment]
Updated
https://drive.google.com/file/d/1t_AgILE-mfkpw7wK-7po_sHfXlawlzV8/view?usp=sharing
