### ISSUE TITLE
Enhance starred accounts message on the left menu

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#478]
I think we should show something like this on Ledger Live instead of the current message.

![image](https://user-images.githubusercontent.com/932636/144550703-4acf1aef-8b65-48c2-97a7-8567a6129e24.png)

**Comment by nicoletting** [comment]
UI Updated @rachelhox 
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/252b9776-140a-4a05-975f-0cd9db881935)
