### ISSUE TITLE
[Airdrop] [Feedback] Highlight the no. of profiles and external account on airdrop page

### ISSUE THREAD

**Issue by kanniec826** [forbole/forbole-x#479]
Suggested to show the number of created profiles and connected external accounts for user to reference on. 

Below is the design Rooty created: 
https://www.figma.com/proto/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?page-id=298%3A459&node-id=1833%3A23077&viewport=241%2C48%2C0.43&scaling=min-zoom&starting-point-node-id=624%3A4083

**Comment by kanniec826** [comment]
@kwunyeung Please note

**Comment by Rooty2020** [comment]
@rachelhox 
https://www.figma.com/proto/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?page-id=1902%3A24432&node-id=1915%3A27145&viewport=241%2C48%2C0.29&scaling=min-zoom&starting-point-node-id=1716%3A24941

**Comment by Rooty2020** [comment]
@RiccardoM 
The airdrop website was updated.
please check, if you have questions pls leave comments. thanks
https://www.figma.com/file/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?node-id=1902%3A24432

**Comment by RiccardoM** [comment]
@Rooty2020 Looks good to me, I think @rachelhox you can implement the graphics as soon as you can, and then ask for the missing data once everything is ready. I will take care of implementing the missing APIs then

**Comment by kanniec826** [comment]
@rachelhox Please help to do this story first, thanks a lot!
