### ISSUE TITLE
Add UI for uploading chain link proof

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#481]
A lot of `LikeCoin` stakers have their keys hosted on a custodial service `AuthCore`. The `LikeCoin` team will let their `LikerLand` app users to sign a message and generate the proof. We should add a UI for those `LikeCoin` stakers to upload their proof and broadcast the transaction to create the chain link and eligible to claim the airdrop.

**Comment by Rooty2020** [comment]
@calvinkei 
we will update some icons next week.
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=4799%3A270641&viewport=241%2C48%2C0.19&scaling=scale-down&starting-point-node-id=4799%3A269014&show-proto-sidebar=1

**Comment by calvinkei** [comment]
@kwunyeung can i have an example/format of the proof generated by likecoin?

**Comment by kwunyeung** [comment]
@williamchong can you provide an example?

**Comment by williamchong** [comment]
https://docs.desmos.network/developers/types/profiles/chain-link/#using-the-cli
I followed the output format of `desmos create-chain-link-json`

`||
{
  "address": {
    "@type": "/desmos.profiles.v1beta1.Bech32Address",
    "value": "cosmos1wfu97hwfv5ukc0xjyutajq9e6w5xkcdprlmyhj",
    "prefix": "cosmos"
  },
  "proof": {
    "plain_text": "636f736d6f733177667539376877667635756b6330786a797574616a713965367735786b636470726c6d79686a",
    "pub_key": {
      "type": "tendermint/PubKeySecp256k1",
      "value": "xxx"
    },
    "signature": "xxx"
  },
  "chain_config": {
    "name": "likecoin"
  }
}
```

**Comment by williamchong** [comment]
Yes the transaction part seems working, however I cannot claim airdrop yet due to graphql congestion issue

**Comment by kwunyeung** [comment]
@williamchong the claim process should be back to normal now. Please test again. Thanks!

**Comment by williamchong** [comment]
@kwunyeung Yes I successfully claimed twice for my accounts, will tell others to try, thanks

**Comment by kwunyeung** [comment]
Awesome!!
