### ISSUE TITLE
Add warning for users before/when using Wallet 

### ISSUE THREAD

**Issue by kanniec826** [forbole/forbole-x#484]
We would like to add warnings for the following situation:

1. Users have to confirm they are using recovery phrase to connect chains when they do so

**Comment by kanniec826** [comment]
@kwunyeung Please note

**Comment by kanniec826** [comment]
@Rooty2020 @nicoletting Please help on the UI

**Comment by Rooty2020** [comment]
@rachelhox 
![Screenshot 2022-01-25 at 3.28.58 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/9af12b7b-0bdd-400a-8d64-4f531ea0f356)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/484?planning-poker) with ZenHub @rachelhox
