### ISSUE TITLE
Improve showing address on Ledger screen

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#485]
We should ask the user to verify the address on the Ledger after we have detected the `Desmos` app is opened.

![image.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/db997090-b9be-4553-9a75-55e82f3cb09a)

We may improve this screen a bit better by showing which address the user is trying to verify. This can be similar to how `Ledger Live` did.

![Screenshot 2021-12-07 at 12.33.48 PM.png](https://images.zenhubusercontent.com/610d12dcbed147b45e407c24/ed8cf58d-df5b-463b-9c9b-2facb1a08a9b)

**Comment by Rooty2020** [comment]
@rachelhox 
https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=5681%3A483467&viewport=241%2C48%2C0.19&scaling=scale-down&starting-point-node-id=5681%3A483467&show-proto-sidebar=1
