### ISSUE TITLE
Chain Link with Keplr + Ledger not supported

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#491]
If the account on Keplr is added from `Ledger`, it will stop after signing with Keplr with the following error.

![image](https://user-images.githubusercontent.com/932636/145146981-008147c5-30e0-490b-8e5f-bab5b57d1812.png)

We may show a warning message and guide users to link with Ledger directly when we catch this error.

Or we should have a warning before selecting Keplr.

**Comment by calvinkei** [comment]
@kwunyeung i cannot reproduce this. when account on keplr is added with ledger i can still connect it. can you check if this issue still persist?

**Comment by kwunyeung** [comment]
@calvinkei just checked and it's working. Closing this now.
