### ISSUE TITLE
Can not connect Keplr

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#495]
@calvinkei 
When I click on approve button on this popup screen.
![Screenshot 2021-12-08 at 6.47.02 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/963dcb86-883f-4e5b-8321-cbbc1f88de98)

It will show the error message
Application error: a client-side exception has occurred (see the browser console for more information).
![Screenshot 2021-12-08 at 6.49.48 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/2fa5f524-c0a7-4023-97af-15c106214323)

**Comment by calvinkei** [comment]
@Rooty2020 can you check if your web version is v0.15.1 and chrome extension is v1.2.0?

**Comment by Rooty2020** [comment]
web version is v0.15.1
chrome extension is v1.2.1
