### ISSUE TITLE
Ledger connection not working on MacOS

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#506]
Yesterday, a user reported that they cannot get pass this screen when using Forbole X website on Chrome and MacOS 10.14.6. They have installed and opened the Desmos app on their Ledger
![IMG_2002](https://user-images.githubusercontent.com/9119016/145552090-87313741-1444-4591-92eb-2d8292db3980.jpg)

**Comment by calvinkei** [comment]
@RiccardoM after almost a month i still cannot reproduce it. i will leave it to backlog and wait until more users report and provide more information

**Comment by kanniec826** [comment]
This need to fix before the completion of rewriting the extension

**Comment by AFDudley** [comment]
I have the same issue, it doesn't even try to connect to the USB device. There's probably a setting in chrome settings:// that needs to be changed, are you testing on a fresh install?
