### ISSUE TITLE
suggest chain to keplr

### ISSUE THREAD

**Issue by calvinkei** [forbole/forbole-x#510]
when the chain does not exist on Keplr (eg, Band), suggest to add that on Keplr
requires the network's rpc, lcd url, native currencies' denom, minimum denom, decimal, bech32 prefix for all account types, etc

**Comment by kwunyeung** [comment]
@calvinkei 

RPC: `https://rpc.band.forbole.com:443`
LCD: `https://lcd.band.forbole.com:443`
Native Denom: `uband`
Min Gas Price: `0.001uband`
Decimal: `6`
Bech32 Prefix: `band`
