### ISSUE TITLE
Enhance starred accounts message on the left menu

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#517]
https://app.zenhub.com/workspaces/forbole-x-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/478

I think we should show something like this on Ledger Live instead of the current message.

![image.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/6571fa25-3da8-4d8f-982f-c9791c9dc4f5)

**Comment by nicoletting** [comment]
starred account animation Json file:
https://drive.google.com/drive/u/1/folders/13pP_EZv_Rj2LXlLBryf1AqNwbtq07Gka
