### ISSUE TITLE
Validators monikers not synched

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#526]
When trying to delegate DSMs, some users have noticed that they couldn't find a specific validator (The Crypto Gateway) that should have been in the list. This happens because the displayed name is different than the one in Big Dipper (fullnode in X and TheCryptoGateway on BD). This bug is not limited to this validator but also another one (and possibly, others as well) - srqn on X and  #0xR4sc4L on BD. 
Probably the reason behind this is because some of them are using the Desmos Profile and maybe X is only fetching the validator moniker.

**Comment by kanniec826** [comment]
thinking of a solution

**Comment by kwunyeung** [comment]
@calvinkei possible if we get all addresses from the validator list and then make a query once using `_in` in the `where` clause?

**Comment by calvinkei** [comment]
@kwunyeung right why cant i think of this lol
ok will work on it this sprint
