### ISSUE TITLE
Add preference page to allow users to select the preference, when they login wallet for the first time.

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#542]
Step 1: Set unlock password
Step 2: Select the method to login
Step 3: Set a wallet moniker & Import Account
**Step 4: Select the preference** (new)

UI updates:

- Add the  preference page

![Screenshot 2022-01-05 at 2.55.21 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/904411c0-44f6-4f9d-b87a-55ee4538f4b0)

![Screenshot 2022-01-05 at 2.55.46 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/3461eef4-dcb2-4af6-afd5-d2565d90878d)

![Screenshot 2022-01-05 at 2.56.16 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/d63bbe80-7435-4473-b4fa-d60cdebea936)

Preference Page after wallet account: 
![Screenshot 2022-01-05 at 2.56.45 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/404b70d4-f25d-436c-b2ad-54e5c24ba922)

![Screenshot 2022-01-05 at 3.06.27 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/3282617c-87ea-4c33-bfe3-7dec16362c50)

**Comment by nicoletting** [comment]
One more update:

- Change the description on all "view Mnemonic phrase page" (add wallet & edit wallet)

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/b4f28259-57e8-4847-9a1b-208e65de9ecc)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/542?planning-poker) with ZenHub @rachelhox
