### ISSUE TITLE
Fix "Vote" button position inside proposals and update the table UI

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#548]
The vote button here is over the parameter. It should be better to move it under it.
![Schermata 2022-01-07 alle 10 21 03](https://user-images.githubusercontent.com/26248202/148522228-ddcddb17-6778-4e1b-84ae-abb7a6b49a34.png)

**Comment by Rooty2020** [comment]
Please follow the UI.
![Screenshot 2022-01-07 at 6.28.48 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/75b7dafe-67cf-4a72-8006-26dddd080d58)
