### ISSUE TITLE
[Proposal] Display the vote cast by the user on proposals

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#549]
We should make possible to easily spot the vote a user made on proposals, in a way they can immediately see if they made any mistake or anything else. So give them a UI feedback with the result they voted for. Something like "Your vote on this proposal is: YES"

**Comment by nicoletting** [comment]
Please refer to the prototype:
- a voting status will be shown after the user voted
- if the user has more than 3 accounts, they can able to click "next" to view more status.
- it will stay at the bottom until the voting period ends

https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=6184%3A429858&viewport=287%2C48%2C0.5&scaling=scale-down&starting-point-node-id=212%3A36&show-proto-sidebar=1

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/5789c973-d1fb-4331-9392-274ca1da1bd3)
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/565ca6c8-ddfb-497c-aa36-9e13a175d414)

**Comment by kwunyeung** [comment]
Tested
