### ISSUE TITLE
Withdraw commission even there is no delegation rewards

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#559]
For a particular case, if the validator is setting 100% commission, the account has 0 reward but only commission, `Withdraw Rewards` would not allow it to continue as it only check if there is delegation rewards.

![image](https://user-images.githubusercontent.com/932636/148929174-e0f08001-1292-43ce-8f30-268535d09496.png)

X should allow validator account to withdraw commission even there is no delegation rewards.

**Comment by kwunyeung** [comment]
Got these errors when withdrawing commission from Ledger on staging.

![image](https://user-images.githubusercontent.com/932636/152950134-5398fd34-76bb-42a4-9b0f-081cb4cef541.png)

**Comment by calvinkei** [comment]
@kwunyeung when did it happen? is it after the extension popup? did the extension UI show anything or crash immediately?

**Comment by kwunyeung** [comment]
@calvinkei after the extension popped up. The errors are from the extension.

**Comment by calvinkei** [comment]
@kwunyeung can i have your validator address?

**Comment by kwunyeung** [comment]
`desmosvaloper17lca9smrdlwkznr92hypzrgsjkelnxeaacgrwq`

**Comment by calvinkei** [comment]
@kwunyeung fixed in v0.18.1 staging

**Comment by kwunyeung** [comment]
Tested.

**Comment by kwunyeung** [comment]
The commission withdrawal is broadcasting a wrong message. It's now the same as withdraw rewards which is `/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward`. The correct message should be `/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission`. The message is as simple as

```
 {
        "@type": "/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission",
        "validator_address": "desmosvaloper17lca9smrdlwkznr92hypzrgsjkelnxeaacgrwq"
 }
```

We can sign the both messages for a validator and it will withdraw both rewards and commission from the validator.

**Comment by calvinkei** [comment]
@kwunyeung fixed and deployed on staging v0.18.2

**Comment by kwunyeung** [comment]
@calvinkei Yes I would like to withdraw both in a single transaction for validators. Should we make it not in two tabs but show "Rewawrds and Commission" if the account is a validator? We can close this issue first and handle it in another issue if that make sense.

**Comment by calvinkei** [comment]
@kwunyeung this involves changes in UI. should we release it in this version and improve the UI later?

**Comment by kwunyeung** [comment]
All working good in production.
