### ISSUE TITLE
Transaction list under Account page is not updating

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#578]
Transaction list under `Account` page is not updating after new transactions are committed to the corresponding account. Suggest to add subscription to this list.

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/578?planning-poker) with ZenHub @rachelhox
