### ISSUE TITLE
Lock Screen Button

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#579]
Got a few feedback asking about signing out the wallet. Looks like people are looking for a way to lock the wallet after use. I suggest to have a `Lock Screen` button which will forget the password and lock the wallet.

**Comment by nicoletting** [comment]
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/3f042238-4a4d-4318-bbdd-b7eb80bb82b9)

- [download icon here](https://drive.google.com/drive/u/1/folders/1p3r2HP9Eu_IuvCZclc3iQxidJROg94oA)

- [to view the prototype plz click me](https://www.figma.com/file/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?node-id=3451%3A201873)

**Comment by nicoletting** [comment]
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/58476155-ab8c-441d-b7c2-cb789ee142cd)

Please also update on extension 🙇🏻‍♀️ @francochau

**Comment by kwunyeung** [comment]
I think the button has to be more prominent. Also look like from user feedback, they would only understand if they see `Sign out`.

**Comment by kwunyeung** [comment]
In that sense, it's either showing a big button with the word `Sign Out` or `Log Out` or an icon showing an "exit"

**Comment by nicoletting** [comment]
Updated above, please see if it is okay🙇🏻‍♀️ @kwunyeung

**Comment by kwunyeung** [comment]
I'm fine with the latest version

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/579?planning-poker) with ZenHub @calvinkei
