### ISSUE TITLE
update description on create/import/edit wallet UI

### ISSUE THREAD

**Issue by nicoletting** [forbole/forbole-x#583]
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/f20ea8cd-ae53-42a6-ad4f-8c7d15be4090)
**Before** :Select one of method that can describe you
**After**: Import wallet or create a new wallet 

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/da99c89b-6330-4ab3-a592-9f866130c643)
**Before:** Select account(s) you want to add
**After:**  Select account(s) you would like to add

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/b997daea-e694-4380-8ab2-12249dc40222)
change the wording from "changed" to "updated"

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/b4f28259-57e8-4847-9a1b-208e65de9ecc)

- Change the description on all "view Mnemonic phrase page" (add wallet & edit wallet)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/583?planning-poker) with ZenHub @rachelhox
