### ISSUE TITLE
[Airdrop] Get a grant button continues to spin endlessly

### ISSUE THREAD

**Issue by RiccardoM** [forbole/forbole-x#590]
After requesting a grant, the button continues to spin endlessly. This gives the user the idea that something is continously loading and it had a lot of people staying there for hours waiting it to end even though it never does. 

I think after clicking the button, the API should be called again every 8 seconds (~ block time) to see whether the returned result is different and update the button status as soon as `has_enough_dsm` is returned to be `true`.

**Comment by calvinkei** [comment]
@RiccardoM are all users facing the same issue or just some of them? there's already a 5s polling interval and I have tested it works. If it doesn't work for you you can inspect the web and check the network tab to see if is fetching every 5s, and what it returns

**Comment by kanniec826** [comment]
Get help from Infra team

**Comment by RiccardoM** [comment]
Looks like it was a very particular case. I've solved it from the backend.
