### ISSUE TITLE
Allow users to set gas manually

### ISSUE THREAD

**Issue by bragaz** [forbole/forbole-x#591]
While making a tx, users can't set the gas manually. This can lead to problems like this one:
![rejected](https://user-images.githubusercontent.com/26248202/151757697-f474f1f4-7f26-43bd-ab19-32f2f4d57732.jpg)

I suggest to add a button "Set gas" directly on the extension to allow users to set it manually. I imagine something like this:
![gas](https://user-images.githubusercontent.com/26248202/151757803-fd28f3c7-1cea-450a-9155-255eebce7092.jpg)

**Comment by kwunyeung** [comment]
@bragaz do you know which tx the user is trying to broadcast. We should have applied gas adjustment to the gas estimate before signing the tx. I'm wondering how much gas is needed for this tx.

Instead of setting a gas value directly, I would suggest showing the gas estimate and allow users to change the gas adjustment with a slider.

**Comment by bragaz** [comment]
@kwunyeung most of the users are facing it while trying to claim rewards.
So a `withdraw-rewards` / `withdraw_all_rewards` transaction.
I've also registered some cases of this problem with the `unbound` transaction

**Comment by kanniec826** [comment]
min 1.5 can adjust more than this amount for the gas fee

**Comment by nicoletting** [comment]
As discussed last time, I found 3 solutions for the UI:
![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/8bcc99fb-bfd4-46ab-8920-b553473549d7)
I think **(C)** is the most suitable and educative one, for serval reasons:
1.  present concept that complex transactions require more gas and the wanted gas range
2. provide 3 buttons for user's daily practice but in the different definition -> "simple, medium, complex"
3. adjustable slider & enable input amount and adjust amount with [+], [-] button. 
 
**to review the prototype please visit** [here](https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=3665%3A212234&node-id=6692%3A447332&viewport=265%2C48%2C0.5&scaling=scale-down&starting-point-node-id=6692%3A446750&show-proto-sidebar=1)
@kwunyeung @kanniec826

**Comment by kanniec826** [comment]
@nicoletting Personally I prefer A

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/591?planning-poker) with ZenHub @nicoletting

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/591?planning-poker) with ZenHub @calvinkei

**Comment by calvinkei** [comment]
actually do we still need to do this? the error is caused by gas fee rounding instead of insufficient gas. 1.5x should be more than enough and no user is reporting this issue again since the fix

**Comment by kwunyeung** [comment]
@calvinkei @nicoletting maybe this should be treated as a separate issue.

My concern is in case `1.5x` is not enough in the gas estimate, there is still option to override the gas amount. So for this case, I prefer a more simple way to set the gas but not having `1.5`, `1.6`, `1.7` for choosing. Having these options are meaningless.

**Comment by nicoletting** [comment]
I've modified the UI and it is now ready:
[view prototype here](https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=335%3A1405&viewport=265%2C48%2C0.25&scaling=scale-down&starting-point-node-id=212%3A36&show-proto-sidebar=1)

- click a "set gas" icon to expand the column
- enter gas
- drag the slider for gas adjustment
- the calculated fee will be updated

please change UI of delegate/ redeledate/ undelegate/ withdraw rewards/ send🙇🏻‍♀️
