### ISSUE TITLE
[Settings]Change twitter account 

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#605]
![Screenshot 2022-02-08 at 12.18.44 PM.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/e56a5726-ced0-4f23-92f5-b9fdf3eb360c)
Change twitter account from @forbole to @ForboleX
https://mobile.twitter.com/ForboleX

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/605?planning-poker) with ZenHub @rachelhox
