### ISSUE TITLE
[Staking]Update voting power design on staking list

### ISSUE THREAD

**Issue by nicoletting** [forbole/forbole-x#618]
- voting power design update

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/e1cf05b2-1b64-427a-b765-c4b0833a81ea)
[View Prototype here](https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=192%3A2&node-id=532%3A476&viewport=265%2C48%2C0.21&scaling=scale-down&starting-point-node-id=212%3A36&show-proto-sidebar=1)

**Comment by Rooty2020** [comment]
@nicoletting 
duplication [#617](uhttps://app.zenhub.com/workspaces/forbole-x-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/617rl)
