### ISSUE TITLE
Add hold over label on the left menu items when the menu is minimized

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forbole-x#627]
Currently users may not know what those icons are if the left menu is minimized.

![image](https://user-images.githubusercontent.com/932636/154641832-ad7bb7af-1308-4f70-9300-ecd8a1c4ca85.png)

Suggest to have hold over label showing the menu labels after mouse cursor holding there for a few seconds.

Label Reference: 

![image.png](https://images.zenhubusercontent.com/610cd72d94b503197fd1700a/ac45c4cb-a371-44cc-bf3c-43ebb5e87e58)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Forbole-X-610d140ec66d6d000fe67c41/issues/forbole/forbole-x/627?planning-poker) with ZenHub @rachelhox

**Comment by nicoletting** [comment]
added hover label.
[view prototype here](https://www.figma.com/proto/w7LpoB8DejNVumjJPDrp7j/Forbole-X-_web-app_1.0?page-id=5607%3A317014&node-id=7084%3A422376&viewport=265%2C48%2C0.25&scaling=min-zoom&starting-point-node-id=7084%3A422376&show-proto-sidebar=1)
