### ISSUE TITLE
[Staging Updates] Update Icons

### ISSUE THREAD

**Issue by Rooty2020** [forbole/forbole-x#665]
Please update settings and eye icons.

<img width="407" alt="Screenshot 2022-04-27 at 11 34 22 AM" src="https://user-images.githubusercontent.com/60619414/165434729-e5acc16d-5490-4dfb-b930-a36bccf4dfcc.png">
<img width="399" alt="Screenshot 2022-04-27 at 11 34 28 AM" src="https://user-images.githubusercontent.com/60619414/165434890-02214896-b61b-4292-9b15-3f480135a052.png">

@nicoletting 
please upload the latest updated icons.

**Comment by nicoletting** [comment]
please download here:
https://drive.google.com/drive/folders/1WmC0M6sCQM2SjyZVxjfcGPNrQmBKTKy5?usp=sharing
